/*
 Autor: Emanuel Lima
 Data: 18/08/2026
 
 Descrição: Esse Script mostra as formas de usar Clasula CASE WHEN

 Versão 1.0

*/

-- CASE 

-- 1° FORMA
SELECT
	LOJA,
	CUPOM,
	DATA,
	COD_CLIENTE,
	VENDEDOR,

	CASE VENDEDOR -- SUBSTITUINDO UM VALOR
	WHEN 'LTZ' THEN 'LUIZ T ZUIM'
	WHEN 'LLP' THEN 'LUIZ LOURENCO PEREIRA'
	END AS [VENDEDOR]
FROM TB_VENDAS

-- 2° FORMA
SELECT
	LOJA,
	CUPOM,
	DATA,
	COD_CLIENTE,
	VENDEDOR,

	CASE
	WHEN VENDEDOR IN('LLP','LTZ','UGB') THEN 'VENDEDORES EXTERNOS'
	END AS [VENDEDOR]
FROM TB_VENDAS

-- CASE USANDO OR
SELECT
	LOJA,
	CUPOM,
	DATA,
	COD_CLIENTE,
	VENDEDOR,

	CASE
	WHEN VENDEDOR = 'LTZ' OR VENDEDOR = 'LLP' THEN 'VENDEDORES EXTERNOS'
	END AS [VENDEDOR]
FROM TB_VENDAS

SELECT * FROM TB_VENDAS